### ISSUE TITLE
Challenge #2 - Enhanced visualisation of atmospheric data

### ISSUE THREAD

**Issue by jwagemann** [esowc/challenges_2019#10]
# Challenge 2
### Enhanced visualisation of atmospheric data

Creation of animations using Earth data:  design, prototype, and implementation.

**Goal**: The goal of the project is to create a set of scripts that will generate earth animations to allow general public to understand the data produced and used at ECMWF (e.g. the evolution of CO2 during a specific year, etc.) 

<br>

| | |
|------------|----------------------------------------------------------------------|
| **Mentors** | Anna Agusti-Paraneda, @milanavuckovic, Pierre Vernier, @sylvielamythepaut , @joaquinval |
| **Skills required** |- Creativity </br> - Video editing </br>- Basic understanding of Earth sciences </br>- Visualisation techniques </br> - Linux |
<hr>

#### What data/system(s) should be used?
The main input data will be the publicly available reanalysis data from Copernicus/ECMWF, and data from satellite sources, such as C02 averaged over the atmospheric column and the fluxes of CO2 at the Earth’s surface (1 year of data, every 3 hours), the visualisation could also make use of aerosols, clouds and winds. Other data such as topography, vegetation type, cities can also be made available. 
ECMWF data are available in the formats GRIB or NetCDF, which can be converted to other formats if needed. 
#### What could be the solution?
Extraordinary visualisations are circulating on YouTube, Twitter, or other social networks. This could be a first source of inspiration: 
- https://www.youtube.com/watch?v=x1SgmFa0r04
- https://www.youtube.com/watch?v=owBBpOW-y30

3D effects could help people understand specific surfaces fluxes and the change of certain atmospheric parameters in time.

The project will consist in, first, designing an animation. Examples of animations that could be shown: 
- The CO2 cycle throughout the year, including the diurnal and seasonal changes associated with the breathing of vegetation and the increasing emissions by human activities. 
- Various forecast parameters: amount of clouds, lightning, precipitation (with different styles for different types of precipitation), wave heights, ocean currents, sea/land surface temperature etc. 
- Various reanalysis parameters: sea ice cover, 2m temperature, wind etc. over long period of time or for some significant events. 

The implementation phase will consist in writing a set of tools, to enable ECMWF to recreate the animation when new data are coming.  

The animations will be displayed on ECMWF’s globe at the entrance of our headquarters in Reading, and published on ECMWF’s social media channels, such as YouTube and Twitter.

![challenge2_image](https://user-images.githubusercontent.com/8168920/51269308-177a1900-19ba-11e9-968a-ce488257b6a6.png)

#### Constraints:
The animations should be delivered as mp4. All deliverables shall be open source and will be made available on GitHub with an open source license. 
The tools should run on a Linux platform and make use of open source software.    
Possible tools: 
- Unity (GUI, available on Windows and Mac)
- Blender (GUI, available on Linux, Windows and Mac) with addon to integrate geographic data  
- GDAL (CLI) 
- Three.js (JavaScript 3D library)

**Comment by RubenRT7** [comment]
(From Email)
Dear Sir/Madam,
 
I write you because I would like to have an information about  “Selected Challenge: #2 - Enhanced visualization of atmospheric data”
 
The “Challenge” states that it is possible to use CO2 data.
“What data/system(s) should be used?
The main input data will be the publicly available reanalysis data from Copernicus/ECMWF, and data from satellite sources, such as C02 averaged over the atmospheric column and the fluxes of CO2 at the Earth’s surface (1 year of data, every 3 hours)”
 
I searched for them and I found some “surface air-sample measurements” available on
https://apps.ecmwf.int/datasets/data/cams-ghg-inversions/
 
Are there some other datasets available?
 
Thank you very much,
Have a nice day,
Enzo Papandrea

**Comment by milanavuckovic** [comment]
Dear Enzo,

Thank you for taking an interest in our ESOWC challenge.

You can find CO2 data from satellite observations in Copernicus Climate Data Store ([CDS](https://cds.climate.copernicus.eu)). All the data in CDS is open and free to use.
There are many other data sets in CDS, but CO2 you can find directly on this link
https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-carbon-dioxide?tab=form

Kind regards,
Milana Vuckovic

**Comment by jwagemann** [comment]
#### REMINDER: Deadline to register and submit your proposal is upcoming Sunday, 21 April at 23:59 GMT!
Application process is a 2-step process:
- You have to first register [here](https://events.ecmwf.int/event/117/registrations/47/), and then
- Submit a proposal under "Call for abstract" [here](https://events.ecmwf.int/event/117/abstracts/).

Applications without a submitted proposal will not be taken under consideration!
We are looking forward to your proposal!
