### ISSUE TITLE
Challenge #4 - Standalone offline interactive 3D globe visualisation widget

### ISSUE THREAD

**Issue by jwagemann** [esowc/challenges_2019#4]
# Challenge 4
### Standalone offline interactive 3D globe visualisation widget

Development of a 3D visualisation application.

**Goal**: Develop a standalone offline interactive 3D globe visualisation widget that can render  ECMWF data provided by ECMWF’s workstation application Metview. It should provide standard zoom/rotate/animate controls, as well as a layer selection control.

<br>

| | |
|------------|----------------------------------------------------------------------|
| **Mentors** | @iainrussell  and @sk-ec  |
| **Skills required** | - Python programming  </br> - Qt programming  </br>- Linux or Mac OS X environment |
<hr>

#### What data/system(s) should be used?
The user environment would be a standalone Qt application written in Python/Qt and able to intercept data and visual definition icon drops from Metview icons. It would then use Metview’s Python interface to generate 2D plots of field data, or a list of 3D point locations for observations (e.g. GeoJSON) and display these on an interactive globe with controls for zoom/rotate/animation and layer selection.
#### What is the current problem/limitation?
Metview is currently limited to a flat map. Even if the user selects a polar projection, they cannot easily move around to view different areas. Additionally, the height dimension of any data is lost. This tool could provide a nice, quick way to view data including observations in their 3D context.
#### What could be the solution?
We would prefer the user interface to be written using Python and Qt, as these are technologies that we are familiar with and would be able to maintain or further develop. Metview is required - its user interface would be one way for users to pass data to the globe, and its Python interface would allow the application to read the data and produce plots and data in formats that could be rendered onto the globe. 
The following pic shows Google Earth with ECMWF data isolines - we’d like something similar as a desktop application!

![challenge4_image](https://user-images.githubusercontent.com/8168920/51268592-6c1c9480-19b8-11e9-9be8-63c6dfb83316.png)

**Comment by MadalinSpoiala** [comment]
Hi! I am interesed in working on this project. Could you please provide me with some contact info so we would be able to discuss the details? 
Thank you!

Madalin Spoiala.

**Comment by jwagemann** [comment]
Hi @MadalinSpoiala ,
freel free to post your questions here. Other applicants might have similar questions. This Github issue is here for discussion.
Julia

**Comment by jwagemann** [comment]
#### REMINDER: Deadline to register and submit your proposal is upcoming Sunday, 21 April at 23:59 GMT!
Application process is a 2-step process:
- You have to first register [here](https://events.ecmwf.int/event/117/registrations/47/), and then
- Submit a proposal under "Call for abstract" [here](https://events.ecmwf.int/event/117/abstracts/).

Applications without a submitted proposal will not be taken under consideration!
We are looking forward to your proposal!
