### ISSUE TITLE
Challenge #6 - Julia-based interface to ECMWF's Integrated Forecasting System single model column

### ISSUE THREAD

**Issue by jwagemann** [esowc/challenges_2019#6]
# Challenge 6
### Julia-based interface to ECMWF's Integrated Forecasting System (IFS) single model column

Development of a Jupyter notebook calling Fortran-based single-column Integrated Forecasting System (IFS) weather prediction software.

**Goal**: Facilitate usage of the single column model of ECMWF's IFS. Showcase how a modern, interactive, development environment can enhance scientific productivity for ECMWF’s Integrated Forecasting System (IFS).

<br>

| | |
|------------|----------------------------------------------------------------------|
| **Mentors** | @mlange05  and @marsdeno |
| **Skills required** | - Julia or Python experience </br> - Some experience with a compiled language desirable |
<hr>

#### What data/system(s) should be used?
We plan to use the OpenIFS code base as a starting point.
#### What is the current problem/limitation?
The current single column model is cumbersome to use and modify, and offers no easy means of visualizing or analyzing results.
#### What could be the solution?
We believe that developing a Jupyter-based work environment would significantly improve ease of use and modification, as well as allow interactive visualization and assessment of results.
#### Possible idea for the implementation:
- Rethink the current Fortran control structure and rewrite it in Julia 
- Interface the necessary Fortran data types to Julia for both easy input specification and easy analysis/visualisation  
- Interface with the Fortran build system to regenerate automatically the necessary objects when the scientific Fortran is changed.

**Comment by tibi77** [comment]
The project needs to be done in Julia or can I do it in python? I have some experience in python but I have not written julia in a long time. Also how do we get aces to the Fortran code? BTW I will love to be part of this project because I think it is time to bring the meteorology and aviation related software to the 20th century industry standard.

**Comment by marsdeno** [comment]
@tibi77 
the project could definitely be done in python, the interactive jupyter aspect is more interesting to us than the implementation language.
The Fortran source code for the single column model is part of the OpenIFS package which we are planning to work with. Access to the OpenIFS source would be granted once the project starts.
And we are very much with you on bringing our software into the 20th (21st is still a dream) century!

On the technical side, we are imagining using something like [f90wrap](https://github.com/jameskermode/f90wrap) or [lfortran](https://github.com/lfortran/lfortran) to call the Fortran control code from the notebook. Some of the minimal requirements to get a demonstrative notebook would be 
- generating the meteorological configuration input from the notebook
- creating wrappers for interactively calling the fortran code
- importing /extracting field data for viz/analysis in the notebook environment

Fire away with any more questions.

**Comment by tibi77** [comment]
I suppose that fortran-magic[1] can be used in the project. Or should I make the wrappers by myself? I would like using it because it is done especially for the Ipython!
[1] https://pypi.org/project/fortran-magic/

**Comment by mlange05** [comment]
@tibi77 Yes, absolutely (and nice find)! Figuring out which open-source tools and packages we can leverage to get to a functioning prototype is the core idea behind this project. Once we get to more advanced topics, like complex data types, we can even try to extend them to get around any limitations we might find.

**Comment by jwagemann** [comment]
#### REMINDER: Deadline to register and submit your proposal is upcoming Sunday, 21 April at 23:59 GMT!
Application process is a 2-step process:
- You have to first register [here](https://events.ecmwf.int/event/117/registrations/47/), and then
- Submit a proposal under "Call for abstract" [here](https://events.ecmwf.int/event/117/abstracts/).

Applications without a submitted proposal will not be taken under consideration!
We are looking forward to your proposal!

**Comment by tibi77** [comment]
Regarding the proposed time-line who can I talk to to make sure that my milestones align with the thinking of the organization?

**Comment by ppalmes** [comment]
I'm not sure i understand correctly the objectives. the notebook interface i think is trivial once you have a julia wrapper for the fortran functions in the compiled libs by using julia's ccall: https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/index.html

Assuming you can translate fortran data types into Julia's data types, further visualization and analysis can be done in Julia running in the notebook using IJulia package. It should be 1% effort for the notebook and 99% effort to write wrappers for some fortran functions needed to process the data.

**Comment by marsdeno** [comment]
@tibi77  I'd be happy to talk about possible milestones. We can either do that on github or you can contact me via email, olivier.marsden@ecmwf.int

**Comment by marsdeno** [comment]
@ppalmes  Mostly agreed, the notebook interface side of things would be the final visible result of the project, but not where most of the work would be. 
Translation of the fortran data types into Julia/python is not actually trivial, as our fortran data types are nested and have some complexity. 
However, a full translation is probably not required, depending on the level at which the interfacing happens.
Rethinking the control structure and writing it in Julia/python is where I see the most flexibility.
